import { useState } from 'react'
import { Check, Copy, Landmark } from 'lucide-react'
import { toast } from 'sonner'

import { Button, Card } from '@/components/ui'

/**
 * Bank transfer details.
 *
 * The instructions string is generated by the `bank-transfer-instructions`
 * function, so this panel only presents it and makes the reference easy to
 * copy. We say plainly that the order is not paid until the money lands —
 * overstating this is the single easiest way to lose a customer.
 */
export function BankTransferPanel({
  instructions,
  reference,
  className,
}: {
  instructions: string
  reference: string
  className?: string
}) {
  const [copied, setCopied] = useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(reference)
      setCopied(true)
      toast.success('Reference copied')
      window.setTimeout(() => setCopied(false), 2500)
    } catch {
      toast.error('Could not copy — select the reference and copy it manually.')
    }
  }

  return (
    <Card className={className}>
      <div className="flex items-start gap-3 border-b border-line p-5">
        <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-bronze/12 text-bronze-dark">
          <Landmark className="size-4.5" aria-hidden />
        </span>
        <div className="min-w-0">
          <h3 className="font-display text-base font-semibold text-ink">Pay by bank transfer</h3>
          <p className="mt-0.5 text-xs leading-relaxed text-muted">
            Transfer to the account below and use the reference exactly as written.
          </p>
        </div>
      </div>

      <div className="space-y-4 p-5">
        <div className="rounded-md border border-line bg-sand/50 p-3.5">
          <p className="text-[0.6875rem] font-semibold uppercase tracking-[0.14em] text-muted">
            Payment reference
          </p>
          <div className="mt-1.5 flex items-center gap-2">
            <p className="min-w-0 flex-1 break-all font-display text-lg font-semibold tabular-nums text-ink">
              {reference}
            </p>
            <Button
              variant="outline"
              size="iconSm"
              onClick={() => void copy()}
              aria-label="Copy payment reference"
            >
              {copied ? (
                <Check className="size-4 text-success" aria-hidden />
              ) : (
                <Copy className="size-4" aria-hidden />
              )}
            </Button>
          </div>
        </div>

        <div className="prose-editorial text-sm">{instructions.split('\n').map((line, index) => (
          <p key={index} className="text-sm leading-relaxed text-ink-soft">
            {line}
          </p>
        ))}</div>

        <p className="rounded-md border border-warning/30 bg-warning/[0.07] p-3.5 text-xs leading-relaxed text-ink">
          Your order is reserved but <strong>not yet paid</strong>. We confirm it the moment the
          transfer shows on our side — usually within a few hours during business days. If it has not
          arrived by the next working day, WhatsApp us with your transfer receipt.
        </p>
      </div>
    </Card>
  )
}
